server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/ticketing-db?user=ticketing-user&password=ticketing.password!
    username: ticketing-db
    password: ticketing.password!
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: sip.2022.unlu@gmail.com
#    password: uqbelcsvfanzavld
#    properties:
#      mail:
#        smtp:
#          auth: true
#          connectiontimeout: 10000
#          timeout: 10000
#          writetimeout: 10000
#          starttls:
#            enable: true
#          ssl:
#            trust: smtp.gmail.com
#  servlet:
#    multipart:
#      max-file-size: 25MB
#      max-request-size: 25MB
#
#jwt-secret: ${jwt-secret}
#jwt-issuer: ${jwt-issuer}
#jwt-expiration-days: ${jwt-expiration-days}
#
#mercadopago:
#  frontend: http://34.133.211.180
#  backend: http://35.184.117.168
#  access-token: TEST-7858724244652929-060822-41b97c015ac370f0e072387aa4e86a1b-1129213662
#
#superadmin-email: admin@admin.com
#superadmin-password: adminadmin
#app-url: http://35.184.117.168